/*
 * Weather API
 * # Introduction WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy. We provide following data through our API:     - Real-time weather - 14 day weather forecast - Historical Weather - Marine Weather and Tide Data - Future Weather (Upto 365 days ahead) - Daily and hourly intervals - 15 min interval (Enterprise only) - Astronomy - Time zone - Location data - Sports - Search or Autocomplete API - Weather Alerts - Air Quality Data - Bulk Request  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!  Try our weather API by using interactive [API Explorer](https://www.weatherapi.com/api-explorer.aspx).  We also have SDK for popular framework/languages available on [Github](https://github.com/weatherapicom/) for quick integrations.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.    Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=YOUR API KEY  
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AstronomyAstro
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-08T07:58:56.667Z")
public class AstronomyAstro {
  @SerializedName("sunrise")
  private String sunrise = null;

  @SerializedName("sunset")
  private String sunset = null;

  @SerializedName("moonrise")
  private String moonrise = null;

  @SerializedName("moonset")
  private String moonset = null;

  @SerializedName("moon_phase")
  private String moonPhase = null;

  @SerializedName("moon_illumination")
  private String moonIllumination = null;

  public AstronomyAstro sunrise(String sunrise) {
    this.sunrise = sunrise;
    return this;
  }

   /**
   * Get sunrise
   * @return sunrise
  **/
  @ApiModelProperty(example = "05:10 AM", value = "")
  public String getSunrise() {
    return sunrise;
  }

  public void setSunrise(String sunrise) {
    this.sunrise = sunrise;
  }

  public AstronomyAstro sunset(String sunset) {
    this.sunset = sunset;
    return this;
  }

   /**
   * Get sunset
   * @return sunset
  **/
  @ApiModelProperty(example = "09:03 PM", value = "")
  public String getSunset() {
    return sunset;
  }

  public void setSunset(String sunset) {
    this.sunset = sunset;
  }

  public AstronomyAstro moonrise(String moonrise) {
    this.moonrise = moonrise;
    return this;
  }

   /**
   * Get moonrise
   * @return moonrise
  **/
  @ApiModelProperty(example = "12:29 AM", value = "")
  public String getMoonrise() {
    return moonrise;
  }

  public void setMoonrise(String moonrise) {
    this.moonrise = moonrise;
  }

  public AstronomyAstro moonset(String moonset) {
    this.moonset = moonset;
    return this;
  }

   /**
   * Get moonset
   * @return moonset
  **/
  @ApiModelProperty(example = "04:01 PM", value = "")
  public String getMoonset() {
    return moonset;
  }

  public void setMoonset(String moonset) {
    this.moonset = moonset;
  }

  public AstronomyAstro moonPhase(String moonPhase) {
    this.moonPhase = moonPhase;
    return this;
  }

   /**
   * Get moonPhase
   * @return moonPhase
  **/
  @ApiModelProperty(example = "Third Quarter", value = "")
  public String getMoonPhase() {
    return moonPhase;
  }

  public void setMoonPhase(String moonPhase) {
    this.moonPhase = moonPhase;
  }

  public AstronomyAstro moonIllumination(String moonIllumination) {
    this.moonIllumination = moonIllumination;
    return this;
  }

   /**
   * Get moonIllumination
   * @return moonIllumination
  **/
  @ApiModelProperty(example = "42", value = "")
  public String getMoonIllumination() {
    return moonIllumination;
  }

  public void setMoonIllumination(String moonIllumination) {
    this.moonIllumination = moonIllumination;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AstronomyAstro astronomyAstro = (AstronomyAstro) o;
    return Objects.equals(this.sunrise, astronomyAstro.sunrise) &&
        Objects.equals(this.sunset, astronomyAstro.sunset) &&
        Objects.equals(this.moonrise, astronomyAstro.moonrise) &&
        Objects.equals(this.moonset, astronomyAstro.moonset) &&
        Objects.equals(this.moonPhase, astronomyAstro.moonPhase) &&
        Objects.equals(this.moonIllumination, astronomyAstro.moonIllumination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sunrise, sunset, moonrise, moonset, moonPhase, moonIllumination);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AstronomyAstro {\n");
    
    sb.append("    sunrise: ").append(toIndentedString(sunrise)).append("\n");
    sb.append("    sunset: ").append(toIndentedString(sunset)).append("\n");
    sb.append("    moonrise: ").append(toIndentedString(moonrise)).append("\n");
    sb.append("    moonset: ").append(toIndentedString(moonset)).append("\n");
    sb.append("    moonPhase: ").append(toIndentedString(moonPhase)).append("\n");
    sb.append("    moonIllumination: ").append(toIndentedString(moonIllumination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

