/*
 * Weather API
 * # Introduction WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy. We provide following data through our API:     - Real-time weather - 14 day weather forecast - Historical Weather - Marine Weather and Tide Data - Future Weather (Upto 365 days ahead) - Daily and hourly intervals - 15 min interval (Enterprise only) - Astronomy - Time zone - Location data - Sports - Search or Autocomplete API - Weather Alerts - Air Quality Data - Bulk Request  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!  Try our weather API by using interactive [API Explorer](https://www.weatherapi.com/api-explorer.aspx).  We also have SDK for popular framework/languages available on [Github](https://github.com/weatherapicom/) for quick integrations.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.    Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=YOUR API KEY  
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ForecastAstro;
import io.swagger.client.model.ForecastDay;
import io.swagger.client.model.MarineHour;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;

/**
 * MarineForecastday
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-11-08T07:58:56.667Z")
public class MarineForecastday {
  @SerializedName("date")
  private LocalDate date = null;

  @SerializedName("date_epoch")
  private Integer dateEpoch = null;

  @SerializedName("day")
  private ForecastDay day = null;

  @SerializedName("astro")
  private ForecastAstro astro = null;

  @SerializedName("hour")
  private List<MarineHour> hour = null;

  public MarineForecastday date(LocalDate date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(example = "2022-07-22T00:00:00.000Z", value = "")
  public LocalDate getDate() {
    return date;
  }

  public void setDate(LocalDate date) {
    this.date = date;
  }

  public MarineForecastday dateEpoch(Integer dateEpoch) {
    this.dateEpoch = dateEpoch;
    return this;
  }

   /**
   * Get dateEpoch
   * @return dateEpoch
  **/
  @ApiModelProperty(example = "1658448000", value = "")
  public Integer getDateEpoch() {
    return dateEpoch;
  }

  public void setDateEpoch(Integer dateEpoch) {
    this.dateEpoch = dateEpoch;
  }

  public MarineForecastday day(ForecastDay day) {
    this.day = day;
    return this;
  }

   /**
   * Get day
   * @return day
  **/
  @ApiModelProperty(value = "")
  public ForecastDay getDay() {
    return day;
  }

  public void setDay(ForecastDay day) {
    this.day = day;
  }

  public MarineForecastday astro(ForecastAstro astro) {
    this.astro = astro;
    return this;
  }

   /**
   * Get astro
   * @return astro
  **/
  @ApiModelProperty(value = "")
  public ForecastAstro getAstro() {
    return astro;
  }

  public void setAstro(ForecastAstro astro) {
    this.astro = astro;
  }

  public MarineForecastday hour(List<MarineHour> hour) {
    this.hour = hour;
    return this;
  }

  public MarineForecastday addHourItem(MarineHour hourItem) {
    if (this.hour == null) {
      this.hour = new ArrayList<MarineHour>();
    }
    this.hour.add(hourItem);
    return this;
  }

   /**
   * Get hour
   * @return hour
  **/
  @ApiModelProperty(value = "")
  public List<MarineHour> getHour() {
    return hour;
  }

  public void setHour(List<MarineHour> hour) {
    this.hour = hour;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarineForecastday marineForecastday = (MarineForecastday) o;
    return Objects.equals(this.date, marineForecastday.date) &&
        Objects.equals(this.dateEpoch, marineForecastday.dateEpoch) &&
        Objects.equals(this.day, marineForecastday.day) &&
        Objects.equals(this.astro, marineForecastday.astro) &&
        Objects.equals(this.hour, marineForecastday.hour);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, dateEpoch, day, astro, hour);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarineForecastday {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    dateEpoch: ").append(toIndentedString(dateEpoch)).append("\n");
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    astro: ").append(toIndentedString(astro)).append("\n");
    sb.append("    hour: ").append(toIndentedString(hour)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

